### ISSUE TITLE
create entry form for Open Mic CFP

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#1]
Last year Open Mic papers was a bit of a mess, having it reside in inboxes isn't a good idea. We should have a form on the site which stores the entries somewhere.

The easiest is perhaps to use something on Google Drive as it helps us not have a database setup for this.

**Comment by Andersos** [comment]
Didnt see this. Well #9 was a dupe. I'll also make a Google Docs with the information if needed =)
