### ISSUE TITLE
Legge på headere på statiske ressurser

### ISSUE THREAD

**Issue by Andersos** [webrebels/web-rebels-2015#15]
Nice to have: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.webrebels.org&tab=desktop

Tilpass nettleserbufring
Angivelse av en utløpsdato eller en maksimumsalder i HTTP-overskriftene for statiske ressurser, gir nettleseren beskjed om å laste inn tidligere nedlastede ressurser fra en lokal disk i stedet for over nettverket.
Tilpass nettleserbufring for følgende ressurser som kan bufres:
https://ssl.google-analytics.com/ga.js (2 timer)

**Comment by leftieFriele** [comment]
Add a cache strategy objects for the https://www.npmjs.com/package/static-asset module

**Comment by trygve-lie** [comment]
We are caching all our own static assets. The only thing which is not being cached according to Googles page speed ranking is Googles own scripts (oh the irony). Its tempting to take that script inhouse but then it might get outdated and I don't see the benefit in going the extra mile to add logic for keeping it up to date to be honest...

**Comment by Andersos** [comment]
Agree with you but when @leftieFriele linked the pagespeed I thought this was something we could try and fix. It's really funny that Google are the once preventing us from getting the 100.

**Comment by trygve-lie** [comment]
What can be fixed are under the mobile tab. All our images is now scaled in the browser and on mobile that slows down stuff. I've added a polyfill for the picture element which makes it possible for us to use responsive images (chrome and opera has it native). An example is added here: https://github.com/webrebels/web-rebels-2015/tree/master/src/examples

**Comment by elisabethirgens** [comment]
I am looking into responsive images! Just need more time to figure out how/what to do.
