### ISSUE TITLE
Vegan / vegetarian info 

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#17]
Either add a.section on the Oslo guide or location / venue about vegan and vegetarian offerings at Mathallen and the venue

**Comment by Andersos** [comment]
So, are we going to add something about Vegetarian offerings? Do you know any? 

http://veg-veg.no/lokalguide/oslo/spisesteder_rent_vegetarisk

Looks like it is closed https://www.facebook.com/theveganwagon

From the review it looks like there are very few vegetarian places http://www.yelp.no/biz/mathallen-oslo at Mathallen
