### ISSUE TITLE
Add Open Graph and Twitter cards meta info to site 

### ISSUE THREAD

**Issue by Andersos** [webrebels/web-rebels-2015#19]
Info can be found here https://dev.twitter.com/cards/overview and http://ogp.me/

**Comment by leftieFriele** [comment]
Great stuff!

**Comment by Andersos** [comment]
When we deploy we need to verify the Twitter cards here https://cards-dev.twitter.com/validator

**Comment by Andersos** [comment]
![skjermbilde 2015-02-18 kl 11 34 05](https://cloud.githubusercontent.com/assets/288977/6245788/67c335e0-b762-11e4-81d8-3ba27194faa2.png)

**Comment by Andersos** [comment]
![skjermbilde 2015-02-18 kl 11 38 25](https://cloud.githubusercontent.com/assets/288977/6245811/b2443ea2-b762-11e4-9440-07bb83074873.png)
