### ISSUE TITLE
iOS not displaying iframe

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#20]
The EventBrite IFrame is not rendering on iOS devices. This got to be fixed before next drop.

**Comment by Andersos** [comment]
Is this not fixed by https://github.com/webrebels/web-rebels-2015/commit/e1255177aa72f6261dcdaa7a889599f06f8bc3b2 ?

**Comment by leftieFriele** [comment]
More like a work around, ideally it would render in iOs too.

**Comment by gregersrygg** [comment]
iOS has a "feature" for iframes that have 100% width. Sounds a bit different than the problem we had in gardr, but this fixed it for us:
`style="width: 1px; min-width: 100%"`

**Comment by leftieFriele** [comment]
No PR? ;)

On Wed, Feb 18, 2015 at 3:03 PM, Gregers Gram Rygg <notifications@github.com
> wrote:

> iOS has a "feature" for iframes that have 100% width. Sounds a bit
> different than the problem we had in gardr, but this fixed it for us:
> style="width: 1px; min-width: 100%"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrebels/web-rebels-2015/issues/20#issuecomment-74868027>
> .
>



-- 
<quote goes here>
-----------------------------------------------------------------------
Espen Dalløkken

**Comment by gregersrygg** [comment]
Sorry. My boss quit his job, so I'm way overloaded with other tasks ;p

**Comment by leftieFriele** [comment]
:)

**Comment by Andersos** [comment]
hehe

**Comment by Andersos** [comment]
So we are no longer selling tickets so this can be closed.
