### ISSUE TITLE
diveristy scholarship 

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#22]
Adding a signup form and information about the scholarship.
- [x] introduction text (7b47aaa47a22348288dcceead279af050a42b14b)
- [x] add /diverstity route with application form with info: name, email, country and description
- [x] setup email sending just like openmic
- [x] add text for sponsors on how they can participate in buying diversity tickets

**Comment by Andersos** [comment]
I just added a form. My suggestion is that the deadline for the scholarship programme is Feb 26th (day before last ticket sale). We will make sure we review all the submissions before the ticket sale on friday and we can just hold back the number of tickets we think we need.

**Comment by leftieFriele** [comment]
That's a pretty tight deadline, not sure if we can do that. We haven't
decided on the number of tickets to make available, I guess that needs to
happen too :)

**Comment by Andersos** [comment]
How many days do you want to review the applications? The deadline should be before the last ticket sale on friday 27th. If we need 2 days to look over stuff den maybe on the 24th or the 25th.

**Comment by Andersos** [comment]
Live version can be seen here: https://www.webrebels.org/scholarship

@leftieFriele suggests renaming the form "Web Rebels Diversity Scholarship"
Deadline for submitting is now February 26th should we move it earlier?

**Comment by Andersos** [comment]
Sponsorship was good. We got 3 extra people to the conference =)
