### ISSUE TITLE
add info about no tickets can be bought

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#23]
we're getting a lot of approaches for people wanting to buy tickets, here is a suggestion for text we can point to:

## Can I purchase extra tickets as a sponsor?

No. We do not sell tickets to anyone. The only tickets that can be bought are the ones available during our ticket sales and the tickets that come with our sponsorship packages.

**Comment by bodil** [comment]
"Yes, by upgrading your sponsor package." :)

Or, more seriously, "No, we do not sell tickets outside of regular ticket sales and the tickets which come included with sponsor packages. Demand for tickets far exceeds the available number of tickets, and we very strongly believe, as a community conference, in giving everyone an equal chance to purchase them."

**Comment by leftieFriele** [comment]
+1 nice one, much better.

**Comment by Andersos** [comment]
I added the suggestion from Bodil. You can reference the text from https://www.webrebels.org/tickets#sponsor

**Comment by Andersos** [comment]
Feel free to reopen if there is anything else =)
