### ISSUE TITLE
Crew and things during the conf-days

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#24]
- Venue contanct: @thomanil 
- Speakers: @trygve-lie 
- Stage: @sveisvei 
- Sponsor contact: @leftieFriele
- Photogaphy: @gregersrygg

Crew day 1:
- @bodil 
- @elisabethirgens 
- @Andersos
- @digitalsadhu (from OneShot)
- @rexxars (from OneShot)

**Comment by gregersrygg** [comment]
:+1: :camera: :boom:

**Comment by leftieFriele** [comment]
@gregersrygg u only coming if it's sunny? ;) I didn't get that one

**Comment by gregersrygg** [comment]
@leftieFriele Yes, and no :snowflake: left in the :mount_fuji: :stuck_out_tongue_winking_eye:

**Comment by Andersos** [comment]
Jobs/Roles and others stuff is added to the Venue spreadsheet.
