### ISSUE TITLE
Move from Nodejitsu

### ISSUE THREAD

**Issue by trygve-lie** [webrebels/web-rebels-2015#25]
Nodejitsu is closing down. We need to move and we've previously tested [Modulus](https://modulus.io/).

Nodejitsu and Modulus are fairly similar when it comes to deploying and running applications. Modulus also have a client for deployment etc and they are even hosting their PaaS on the same cloud and data centers as Nodejitsu. 

Though; there are some differences to keep in mind:

- Modulus does not seem to use build in functionality in npm such as Nodejitsu does. Due to this basic things as prehooks on `npm start` etc does not work.
- Modulus does not seem to have a prehook when deploying. Iow; always remember to manually run `npm run min` to make sure assets are minified before deployment.
- Modulus does not bump version numbers in package.json or keep a snapshot of earlier versions.

On the good side Modulus are / have:

- Half the price of Nodejitsu.
- Alerts on server events like crashing.
- Process statistics.
- Autoscaling based on metrics.
- Node.js version 12 and a proxy with a up to date SSL terminator.

In writing the current status on moving from Nodejitsu to Modulus are:

- [x] Appended new wildcard SSL certificate. 
- [x] Deployed website to Modulus.
- [x] Pointed webrebels.org to Modulus in DNS (no more forward to www.).
- [x] Pointed www.webrebels.org to Modulus in DNS.
- [x] Stopped website at Nodejitsu to see if we get any complaints (In case DNS updates is very slow somewhere).
- [x] Downloaded all invoices from Nodejitsu account.
- [x] Delete the Nodejitsu account.

**Comment by leftieFriele** [comment]
Awesome job! We should perhaps create a deploy run script which bumps
versions and runs minifying at some point.

**Comment by trygve-lie** [comment]
@leftieFriele Yes we should.

Our account at Nodejitsu are now deleted.
