### ISSUE TITLE
archive 2014 site to gh-pages

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2015#6]
the old site currently runs as a daemon on Nodejitsu.
we should make it a gh-pages site like the other old ones.
https://github.com/webrebels/web-rebels-2014/i

**Comment by leftieFriele** [comment]
@Andersos du har jo sort-belte i GH pages, kanskje du kunne sett på denne?

**Comment by Andersos** [comment]
I can do this. What is our domain name registrar again?

**Comment by leftieFriele** [comment]
NameCheap

**Comment by leftieFriele** [comment]
Done, I moved everything onto a GH-pages branch and documented the process on the wiki :)

https://github.com/webrebels/rebeladmin/wiki/Techincal-stuff

**Comment by Andersos** [comment]
Good job and nice that you documented it =)
